apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: computes.cncf.learning.org
spec:
  group: cncf.learning.org
  names:
    kind: Compute
    plural: computes
  claimNames:
    kind: LabCompute
    plural: labcomputes
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                type: object
                properties:
                  diskSizeGB:
                    type: integer
                required:
                - diskSizeGB
            required:
            - parameters
