apiVersion: compute.gcp.upbound.io/v1beta1
kind: Instance
metadata:
  annotations:
    meta.upbound.io/lfclass-id: compute/v1beta1/instance
  labels:
    testing.upbound.io/lfclass-name: cp_instance
  name: cp-instance
spec:
  forProvider:
    bootDisk:
      - initializeParams:
          - image: ubuntu-os-pro-cloud/ubuntu-pro-2204-lts
            size: 20
            type: pd-balanced
    machineType: e2-standard-2
    metadata:
      environment: lfclass
      ssh-keys: |
        acll19@gmail.com:ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIIFM3WD+62gqrdsRpwN+xcUQvq8/ToQQZSdSvJrk9MgZ acll19@gmail.com
    metadataStartupScript: echo 'Upbound!' > /test.txt
    networkInterface:
      - network: lfclass
        subnetwork: lfclass
        accessConfig:
          - {}
    tags:
      - lfclass
      - cncf
    zone: europe-west10-b
  providerConfigRef:
    name: gcp-default
